// Ultracortex Mark IV HEADSET
// https://cdn.shopify.com/s/files/1/0613/9353/files/upgrade-electrode-locations-wide.jpg?2465756622304790975

// Layout for Fz, Cz, P3, Pz, P4, O1, Oz, O2

const ultracortex01 = [
    {
        label: 'Fz',
        theta: 0,
        radius: 0.253,
        x: 60.7,
        y: 0,
        z: 59.5,
        sph_theta: 0,
        sph_phi: 44.4,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'Cz',
        theta: 0,
        radius: 0,
        x: 0,
        y: 0,
        z: 85,
        sph_theta: 0,
        sph_phi: 90,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'P3',
        theta: -140,
        radius: 0.345,
        x: -57.6,
        y: 48.2,
        z: 39.9,
        sph_theta: 140,
        sph_phi: 28,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'Pz',
        theta: 180,
        radius: 0.253,
        x: -60.7,
        y: 0,
        z: 59.5,
        sph_theta: -180,
        sph_phi: 44.4,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'P4',
        theta: 140,
        radius: 0.344,
        x: -57.6,
        y: -48.1,
        z: 39.9,
        sph_theta: -140,
        sph_phi: 28,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'O1',
        theta: -162,
        radius: 0.515,
        x: -80.8,
        y: 26.1,
        z: -4,
        sph_theta: 162,
        sph_phi: -2.7,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'Oz',
        theta: 180,
        radius: 0.507,
        x: -85,
        y: 0,
        z: -1.79,
        sph_theta: -180,
        sph_phi: -1.2,
        sph_radius: 85,
        type: 'EEG',
      },
      {
        label: 'O2',
        theta: 162,
        radius: 0.515,
        x: -80.8,
        y: -26.1,
        z: -4,
        sph_theta: -162,
        sph_phi: -2.7,
        sph_radius: 85,
        type: 'EEG',
      },
];

export const minV = 9;
export const maxV = 15;
export default ultracortex01;
